spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: VehicleController
          uri: http://localhost:8002
          predicates: Path=/vehicle/**
        - id: AdminController
          uri: http://localhost:8002
          predicates: Path=/admin/**
        - id: LoginController
          uri: http://localhost:8002
          predicates: Path=/login
        - id: FenceController
          uri: http://localhost:8001
          predicates: Path=/fence/**
        - id:  RepairManagementController
          uri: http://localhost:8001
          predicates: Path=/repairManagement/**
        - id: VehicleUsageController
          uri: http://localhost:8001
          predicates: Path=/vehicleUsage/**

  web:
    resources:
      add-mappings: true


server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
      fetch-registry: true

